from .pantryCreateView import PantryCreateView
from .pantryListView import PantryListView
from .productAddView import ProductAddView
from .detailPantryProductsView import DetailPantryProductsView
from .shoppingListCreateView import ShoppingListCreateView
from .productEditView import ProductEditView
from .wishListAddProductView import WishListAddProductView