# Generated by Django 4.0.5 on 2022-07-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alacena', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pantry',
            old_name='replenish_Rate',
            new_name='replenish_rate',
        ),
    ]
