# Generated by Django 4.0.5 on 2022-07-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alacena', '0002_rename_replenish_rate_pantry_replenish_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantry',
            name='replenish_rate',
            field=models.CharField(choices=[('Q', 'Quincenal'), ('M', 'Mensual')], default='M', max_length=1, verbose_name='Frecuencia de compra'),
        ),
    ]
