# Generated by Django 4.0.5 on 2022-07-14 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alacena', '0003_alter_pantry_replenish_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpantry',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de vencimiento'),
            preserve_default=False,
        ),
    ]
