# Generated by Django 4.0.5 on 2022-07-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alacena', '0007_alter_productpantry_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpantry',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='productpantry',
            name='first_update_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Agregado'),
        ),
    ]
